apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sql-replica
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 387584877503.dkr.ecr.us-east-1.amazonaws.com/my-sql:v0.3
        name: sql-replica
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        ports:
        - containerPort: 3306